[versions]
kotlin = "2.3.0"
loom = "1.14-SNAPSHOT"
snakeyaml = "2.5"
gson = "2.13.2"
spotless = "8.1.0"
prettier = "3.7.4"
prettierPluginToml = "2.0.6"
googleJavaFormat = "1.33.0"
ktlint = "1.8.0"
fabricLoader = "0.18.4"
fabricKotlin = "1.13.8+kotlin.2.3.0"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
minecraft = { module = "com.mojang:minecraft" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api" }
fabricKotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricKotlin" }
carpet = { module = "maven.modrinth:carpet" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
