[versions]
mod = "2.0.0"
minecraft = "1.21.10"
kotlin = "2.2.21"
yarn = "1.21.10+build.3"
loom = "1.14-SNAPSHOT"
snakeyaml = "2.5"
spotless = "8.1.0"
prettier = "3.7.4"
prettierPluginToml = "2.0.6"
googleJavaFormat = "1.33.0"
ktlint = "1.8.0"
fabric-loader = "0.17.3"
fabric-kotlin = "1.13.7+kotlin.2.2.21"
carpet = "1.4.188"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
carpet = { module = "maven.modrinth:carpet", version.ref = "carpet" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
