[versions]
mod = "2.0.0"
minecraft = "1.21.10"
yarn = "1.21.10+build.3"
loom = "1.14-SNAPSHOT"
fabric-loader = "0.17.3"
fabric-api = "0.138.3+1.21.10"
fabric-kotlin = "1.13.7+kotlin.2.2.21"
kotlin = "2.2.21"
carpet = "1.4.188"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
carpet = {module="maven.modrinth:carpet",version.ref="carpet"}